### ISSUE TITLE
Lite plan doesn't work on IBM Cloud

### ISSUE THREAD

**Issue by NorhanKhaled** [ibm-cloud-docs/Log-Analysis-with-LogDNA#10]
I tried to create a new logging instance on LogDNA service on IBM cloud , although I chose lite plan It was always failing with error message

"Your account does not allow the use of non-lite plans. You can upgrade by adding a credit card to your account or you can select the lite plan if it's available." 

<img width="689" alt="log DNA error" src="https://user-images.githubusercontent.com/21022185/62575793-38498380-b8a4-11e9-8c4c-f6c21f6254d9.PNG">

**Comment by lopezdsr** [comment]
Please, open a support ticket.
