### ISSUE TITLE
Kubernetes agent using deprecated api version

### ISSUE THREAD

**Issue by macarpen** [ibm-cloud-docs/Log-Analysis-with-LogDNA#12]
The LogDNA agent DaemonSet resources linked in this [document](https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-config_agent#config_agent_kube_script) (for instance https://assets.us-south.logging.cloud.ibm.com/clients/logdna-agent-ds-private.yaml) use the `extensions/v1beta1` API version which is deprecated beginning with Kubernetes 1.16 (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).  The fix is to migrate these to use the `apps/v1` API version, which is available since Kubernetes v1.9.

**Comment by lopezdsr** [comment]
fixed
