### ISSUE TITLE
Monitoring the logdna and alerting

### ISSUE THREAD

**Issue by sainathkeesari** [ibm-cloud-docs/Log-Analysis-with-LogDNA#15]
Hello, Is there any way to get the usage alerts for the logdna with automation (terraform) or may be monitoring the usage, with any monitoring tool? I've gone through this https://cloud.ibm.com/docs/Activity-Tracker-with-LogDNA?topic=logdnaat-alerts there it said alerts are configured only by webUI, at least I have not find any other way automating it?

**Comment by lopezdsr** [comment]
Alerts can only be configured through the LogDNA web UI.
