### ISSUE TITLE
Cloud Functions is missing in the list of Cloud Services

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/Log-Analysis-with-LogDNA#17]
Cloud Functions is missing in the list of Cloud Services
https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-cloud_services

Cloud Functions should be listed as it is mentioned
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-logs#logs_logdna

**Comment by lopezdsr** [comment]
fixed
