### ISSUE TITLE
Doc is unclear about how to assign/check access

### ISSUE THREAD

**Issue by natashadsilva** [ibm-cloud-docs/Log-Analysis-with-LogDNA#18]
1. In this section: https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-monitor_cfapp_logs#monitor_cfapp_logs_prereqs
It says 
>Your IBMID must have assigned IAM policies for each of the following resources. For example, to work in the US-south region and in the default resource group, you need the following permissions...

But it does not say how to get those permissions and where to go in the IBM Cloud UI to do so. It is very confusing to try to figure out how to do so from the Account page.

2. I came to this page because my CF app is showing an alert that I should switch to LogDNA. I followed the steps in the first section but a) the UI is out of date with what the instructions say. 
For example, it says to look for "Configure platform services logs. " but on my page I only have "Configure platform logs." Are those the same?

**Comment by lopezdsr** [comment]
I have fixed the issues. Thank you.
