### ISSUE TITLE
Steps to Export logs not very clear

### ISSUE THREAD

**Issue by rakshith-pibm** [ibm-cloud-docs/Log-Analysis-with-LogDNA#7]
In https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-export 
under `Exporting logs programmatically by using the API` section one of the steps is 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/46721470/59883480-daf08600-937a-11e9-8a3a-525748fdc733.png">.

* But on LogDNA it does not have Observability
<img width="463" alt="image" src="https://user-images.githubusercontent.com/46721470/59883643-62d69000-937b-11e9-9cbd-7632a80ab92f.png">

**Comment by hikarimn** [comment]
The correct step is
 b. select the **Configuration** icon > **Organization**

**Comment by lopezdsr** [comment]
fixed
